### ISSUE TITLE
The engine "node" is incompatible with this module. Expected version ">=14". Got "12.18.4"

### ISSUE THREAD

**Issue by Stradivario** [hugomrdias/iso-url#179]
I am having troubles installing `ipfs` with node 12.18.4.

https://github.com/hugomrdias/iso-url/blob/6fdae85368550d36926eaae3d14f8cfc5dc5844d/package.json#L10

```bash
error iso-url@1.1.4: The engine "node" is incompatible with this module. Expected version ">=14". Got "12.18.4"
```

Does this mean that people with lower versions than 14 cannot use this librar ?

Versions
Node version: 12.18.4
Ubuntu 20.04
IPFS: 0.54.2

**Comment by hugomrdias** [comment]
should be fixed in the latest release

**Comment by flux627** [comment]
Is there any reason node 10 would not work with this package?

**Comment by hugomrdias** [comment]
probably not
